<footer>
	<section>
		<ul class="fleft">
			<li><a href="#">Why Starfish</a></li>
			<li><a href="#">Products and Services</a></li>
			<li><a href="#">Our Portfolio</a></li>
			<li class="last"><a href="#">About Starfish</a></li>
		</ul>
		<aside class="fright">
			<a target="_blank" class="facebook" href="https://www.facebook.com/StarfishWebDesignPhilippines">facebook</a>
			<a target="_blank" class="twitter" href="http://www.twitter.com">twitter</a>
		</aside>
	</section>
</footer>